// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhPThMz3bRovEw4QDLwyk1ryVoB1n6boI',
    appId: '1:160878176419:web:13c8b7f8a78afd590ff716',
    messagingSenderId: '160878176419',
    projectId: 'fire-evacuation-for-disable',
    authDomain: 'fire-evacuation-for-disable.firebaseapp.com',
    storageBucket: 'fire-evacuation-for-disable.appspot.com',
    measurementId: 'G-0VRS903GD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAfoLnpTaryS9c87fYWY3MR9Gb3qxbjk',
    appId: '1:160878176419:android:72edf6897e1a858a0ff716',
    messagingSenderId: '160878176419',
    projectId: 'fire-evacuation-for-disable',
    storageBucket: 'fire-evacuation-for-disable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvez_Hsip4WHXVmYvdgA-AxbcVKl-te1I',
    appId: '1:160878176419:ios:0fbf233fc2b4fd4d0ff716',
    messagingSenderId: '160878176419',
    projectId: 'fire-evacuation-for-disable',
    storageBucket: 'fire-evacuation-for-disable.appspot.com',
    iosBundleId: 'com.example.fireEvacuationAssistanceForDisabled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvez_Hsip4WHXVmYvdgA-AxbcVKl-te1I',
    appId: '1:160878176419:ios:0fbf233fc2b4fd4d0ff716',
    messagingSenderId: '160878176419',
    projectId: 'fire-evacuation-for-disable',
    storageBucket: 'fire-evacuation-for-disable.appspot.com',
    iosBundleId: 'com.example.fireEvacuationAssistanceForDisabled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhPThMz3bRovEw4QDLwyk1ryVoB1n6boI',
    appId: '1:160878176419:web:615c171c74dfdf780ff716',
    messagingSenderId: '160878176419',
    projectId: 'fire-evacuation-for-disable',
    authDomain: 'fire-evacuation-for-disable.firebaseapp.com',
    storageBucket: 'fire-evacuation-for-disable.appspot.com',
    measurementId: 'G-9G4ZDTT87K',
  );

}